### ISSUE TITLE
Code for Data Preprocessing

### ISSUE THREAD

**Issue by zll1995-nlp** [xcfcode/PLM_annotator#1]
Hello, can you release the code for giving annotations about keywords extraction, redundancy detection, and topic segmentation? We want to process some new datasets. 

Thanks!

**Comment by xcfcode** [comment]
Thanks for your attention, sure, the codes are under construction. I will release them as soon as possible.  It may take some time😓

**Comment by bobycv06fpm** [comment]
Hi XcfCode,
Could you please release the code for annotating
-  [TS],
- [RDD], 
- #KEY# 
This would help us well.
Thank you.

**Comment by xcfcode** [comment]
Sure, I will release the code. 
Struggle with many things, slow progress.....

**Comment by bobycv06fpm** [comment]
Thank you. 
Wish you solve those struggles.
BTW, is there a way to contact you other than here?
Regards,

**Comment by xcfcode** [comment]
hi, via xiachongfeng@ir.hit.edu.cn

**Comment by bobycv06fpm** [comment]
@xcfcode 
Thank you

**Comment by xcfcode** [comment]
@zll1995-nlp @bobycv06fpm sorry for the (very) late update, please refer to https://github.com/xcfcode/PLM_annotator/tree/main/annotator
