### ISSUE TITLE
关于Topic Segmentation代码部分的问题

### ISSUE THREAD

**Issue by skpig** [xcfcode/PLM_annotator#4]
您好！很感谢你们提供的开源代码。在查看topic_segmentation代码的过程中，我注意到你们筛去了第一和第二句utterance，请问一下是出于什么目的呢？
https://github.com/xcfcode/PLM_annotator/blob/2018eb887b2b2badd138ecfc33831582f29cd37b/annotator/annotate.py#L175-L176

**Comment by xcfcode** [comment]
Hi，感谢您的关注。
* 不考虑第一句话是因为第一句话的loss是人为设定的（第一句话没有上文可以预测该句），因此不具备参考价值。
https://github.com/xcfcode/PLM_annotator/blob/2018eb887b2b2badd138ecfc33831582f29cd37b/annotator/get_loss.py#L66-L70
* 不考虑第二句话是基于观察的人为规则设定。
