### ISSUE TITLE
Max sentence length shouldn't exceed 800

### ISSUE THREAD

**Issue by lxx909546478** [xcfcode/PLM_annotator#6]
I download your model and put it in ckpt to reproduce your reslults, but it runs error "max sentence length shouldn't exceed 800". I used the data download from [here](https://drive.google.com/drive/folders/1wLea1LdEv1jFQMtXr3bXJFiKvZnrGQLO?usp=sharing), and ran bpe.sh and binarise.sh to preprocess them. If there is any wrong? I would appreciate if got your reply.

**Comment by xcfcode** [comment]
Hi, could you please list some detailed commands? Which script produces the error "max sentence length shouldn't exceed 800"?

**Comment by lxx909546478** [comment]
> Hi, could you please list some detailed commands? Which script produces the error "max sentence length shouldn't exceed 800"?

Thanks for your reply. After preprocessing the data, download samsum.pt and put it in ckpt, then run infer. sh, it will report the error.

**Comment by lxx909546478** [comment]
> Hi, could you please list some detailed commands? Which script produces the error "max sentence length shouldn't exceed 800"?

And I use the data download from your link, when trying to train my own model(running the train.sh), it also report this error. But when I change the max_tokens to 1000, it will work. If there is any error when preprocessing the data?

**Comment by xcfcode** [comment]
After offline communication, this problem may be caused by BPE.
