### ISSUE TITLE
Special Tokens Representation

### ISSUE THREAD

**Issue by ouyhlan** [xcfcode/PLM_annotator#8]
Hello! Do these special tokens have special representations while doing the bpe tokenization? Or just treat them as a normal word. Because I haven't found any of the `##KEY##` `[TS]` `[RDD]` in the encoder.json which is provided by your Google Drive.
I would appreciate if got your reply. @xcfcode

**Comment by xcfcode** [comment]
Hi, these special tokens do not have unique representations. we treat them as normal words and perform BPE.
